name: ♻️ Ultimate README Updater

on:
  schedule:
    - cron: "0 1 * * *"  # daily ~01:13 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- GitHub Metrics Dashboard ---
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GH_TOKEN }}
          user: mnsuhairil
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kuching
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          plugin_followup: yes
          plugin_stars: yes

      # --- Commit & Push changes ---
      - name: Commit & push
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: refresh README (metrics/waka/tip/quote/theme)"
            git push
          else
            echo "No changes"
          fi
